### ISSUE TITLE
[FEAT] 기록 작성 V2 개발

### ISSUE THREAD

**Issue by SuniDev** [Moon-Duck-Org/MoonDuckFE-iOS#15]
## 💡 요약
- 새로운 기록 작성 화면을 개발

## ✅ To-Do
- [ ] 기록 작성 선택 UI
- [ ] 카테고리 검색 UI
- [ ] 카테고리 검색 영화 API
- [ ] - 책 API
- [ ] - 드라마 API
- [ ] - 공연 API
- [ ] 기록 작성 UI
- [ ] 기록 작성 API
