### ISSUE TITLE
[FEAT] 홈 화면 비지니스 로직 및 API 연동

### ISSUE THREAD

**Issue by SuniDev** [Moon-Duck-Org/MoonDuckFE-iOS#5]
## 💡 요약
- 홈 화면 비지니스 로직 및 API 연동

## ✅ To-Do
- [x] 카테고리 기능
- [x] 보드 리스트 API 연동
- [x] 정렬 기능
- [x] 이미지 페이징 기능
- [x] 더보기 버튼 연결
- [x] 추가 버튼 연결
